name: myfile
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dotted_border: ^3.1.0
  flutter_svg: ^2.2.2
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_gen:
  integrations:
    image: true
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/img/icons/
    - assets/img/posts/large/
    - assets/img/posts/small/
    - assets/img/stories/
    - assets/img/background/


  fonts:
    - family: avenir
      fonts:
        - asset: assets/fonts/AvenirLTProBook.otf
          weight: 200
        - asset: assets/fonts/AvenirLTProRoman.otf
          weight: 300
        - asset: assets/fonts/AvenirLTProMedium.otf
          weight: 400
        - asset: assets/fonts/AvenirLTProHeavy.otf
          weight: 700
